version: '3.8'

services:
  ocpp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # OCPP WebSocket port
      - "9001:9001"  # API port
    environment:
      - OCPP_HOST=0.0.0.0
      - OCPP_WEBSOCKET_PORT=9000
      - OCPP_API_PORT=9001
      - OCPP_SYSTEM_NAME=ocpp-central
      - OCPP_HEARTBEAT_INTERVAL=60
      # External Database configuration (required for all logging)
      - DB_TYPE=postgres
      - DB_HOST=${DB_HOST:-database.example.com}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-securepassword}
      - DB_NAME=${DB_NAME:-ocpp_server}
      - DB_SSL_MODE=${DB_SSL_MODE:-require}
    volumes:
      - ocpp-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:9001/api/status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  ocpp-data: